name: Update Credly badges

on:
  schedule:
    - cron: "17 7 * * *" # daily at 07:17 UTC (adjust if you like)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@v3
        with:
          # Your Credly profile slug from the URL you sent:
          # https://www.credly.com/users/jason-gardner.a0afe0ad/badges
          CREDLY_USER: "jason-gardner.a0afe0ad"
          README_FILE: "README.md"           # defaults to README.md
          BADGE_SIZE: "110"                  # 110px icons (looks good on GH)
          SORT_BY: "issued_at"               # newest first
