name: Update Credly badges

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright
        run: |
          npm i -y playwright
          npx playwright install --with-deps chromium

      - name: Render & inject badges
        run: |
          node - <<'JS'
          const fs = require("fs");
          const { chromium } = require("playwright");

          (async () => {
            const url = "https://www.credly.com/users/jason-gardner.a0afe0ad/badges";
            const browser = await chromium.launch({ headless: true });
            const page = await browser.newPage();

            // Faster + reliable loading
            await page.goto(url, { waitUntil: "domcontentloaded" });

            // Credly loads badges lazily; keep clicking "See all" / "Load more" if present
            for (let i = 0; i < 20; i++) {
              // wait a little for network/JS to populate
              await page.waitForTimeout(800);
              const more = await page.$('button:has-text("See all") , button:has-text("Load more")');
              if (!more) break;
              await more.click();
            }

            // Give the page a final moment to settle
            await page.waitForTimeout(1500);

            // Collect badges: anchor + image
            const cells = await page.evaluate(() => {
              // Image CDN hint + ensure we get clickable links
              const anchors = Array.from(document.querySelectorAll('a[href*="/badges/"] img[src*="images.credly.com"]'))
                .map(img => {
                  const a = img.closest("a");
                  if (!a) return null;
                  const alt = (img.getAttribute("alt") || "Badge").replace(/"/g, "");
                  const src = img.getAttribute("src");
                  const href = a.getAttribute("href");
                  if (!src || !href) return null;
                  const link = href.startsWith("http") ? href : ("https://www.credly.com" + href);
                  return `<a href="${link}"><img src="${src}" alt="${alt}" height="88"></a>`;
                })
                .filter(Boolean);

              // De-dupe just in case
              return [...new Set(anchors)];
            });

            const html = `<p align="left">\n  ${cells.join("\n  ")}\n</p>\n`;

            // Inject into README between markers
            const readmePath = "README.md";
            const readme = fs.readFileSync(readmePath, "utf8");
            const pattern = /(<!--START_SECTION:badges-->)([\s\S]*?)(<!--END_SECTION:badges-->)/m;
            const replaced = readme.replace(pattern, `$1\n${html}$3`);
            fs.writeFileSync(readmePath, replaced, "utf8");

            console.log(`Extracted ${cells.length} badges.`);
            await browser.close();
          })().catch(e => { console.error(e); process.exit(1); });
          JS

      - name: Commit changes (if any)
        run: |
          if git diff --quiet README.md; then
            echo "No README changes."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update Credly badges"
          git push
