# .github/workflows/credly-badges.yml
name: Update Credly badges

on:
  schedule:
    - cron: "17 7 * * *"   # daily at 07:17 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update README with Credly badges
        uses: pemtajo/badge-readme@3.1.0   # or @main
        with:
          CREDLY_USER: "jason-gardner.a0afe0ad"
          NUMBER_LAST_BADGES: 0            # 0 = all badges
